---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robots-ssh-client
  labels:
    app: ssh-client-pod
    group: robot-common-group
    robotType: simulated
spec:
  selector:
    matchLabels:
      app: ssh-client-pod
      group: robot-common-group
      robotType: simulated
  replicas: 1
  template:
    metadata:
      labels:
        app: ssh-client-pod
        group: robot-common-group
        robotType: simulated
    spec:
      containers:
        - name: client-container
          image: >-
            394603622351.dkr.ecr.eu-central-1.amazonaws.com/5g-era-workshop:webssh-client-1.5.3
          imagePullPolicy: Always
          env:
            - name: GAZEBO_MASTER_URI
              valueFrom:
                configMapKeyRef:
                  name: robots-common-env-configmap
                  key: master.uri.gazebo.local
            - name: ROS_MASTER_URI
              valueFrom:
                configMapKeyRef:
                  name: robots-common-env-configmap
                  key: master.uri.ros
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
