---
apiVersion: v1
kind: Service
metadata:
  name: console-web-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8888
      targetPort: 80
      protocol: TCP
  selector:
    app: ssh-client-pod
    group: robot-common-group
    robotType: simulated
