---
apiVersion: v1
kind: Service
metadata:
  name: robot-gazebo-web
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      #nodePort: 30081
      protocol: TCP
  selector:
    app: gazebo-web-pod
    group: robot-common-group
    robotType: simulated
