---
apiVersion: v1
kind: Service
metadata:
  name: robot-gazebo-client-vnc
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: gazebo-client-pod
    group: robot-common-group
    robotType: simulated
