---
apiVersion: v1
kind: Service
metadata:
  name: robots-ros-master-service
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
    - name: ros
      port: 11311
      protocol: TCP
  selector:
    app: ros-master-pod
    group: robot-common-group
    robotType: simulated
