---
apiVersion: v1
kind: Service
metadata:
  name: robots-ssh-server
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
      protocol: TCP
  selector:
    app: ssh-server-pod
    group: robot-common-group
    robotType: simulated
